# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
guard :shell do
  watch(/(.*).swift/) do |m|
    swift_file = m[0]
    unless swift_file =~ /^\.#/
      puts
      puts
      puts
      puts "Running #{swift_file}"
      puts `xcrun swift #{swift_file} -sdk $(xcrun --show-sdk-path --sdk macosx)`
    end
  end
end
